-- MySQL Script generated by MySQL Workbench
-- Thu Jun 21 23:39:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aventon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aventon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aventon` DEFAULT CHARACTER SET latin1 ;
USE `aventon` ;

-- -----------------------------------------------------
-- Table `aventon`.`tipovehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aventon`.`tipovehiculo` (
  `idtipoVehiculo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoVehiculo`),
  UNIQUE INDEX `idtipoVehiculo_UNIQUE` (`idtipoVehiculo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aventon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aventon`.`usuario` (
  `nombre` VARCHAR(40) NOT NULL,
  `apellido` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `descripcion` VARCHAR(280) NULL DEFAULT NULL,
  `tarjeta` VARCHAR(30) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `nacionalidad` VARCHAR(30) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `administrador` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aventon`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aventon`.`vehiculo` (
  `idvehiculo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `patente` VARCHAR(10) NULL DEFAULT NULL,
  `cantidadAsientos` TINYINT(4) NOT NULL,
  `idtipoVehiculo` INT(10) UNSIGNED NOT NULL,
  `idusuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idvehiculo`),
  UNIQUE INDEX `idvehiculo_UNIQUE` (`idvehiculo` ASC),
  INDEX `fk_vehiculo_tipoVehiculo1_idx` (`idtipoVehiculo` ASC),
  INDEX `fk_vehiculo_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_vehiculo_tipoVehiculo1`
    FOREIGN KEY (`idtipoVehiculo`)
    REFERENCES `aventon`.`tipovehiculo` (`idtipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aventon`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aventon`.`viaje` (
  `idviaje` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `origen` VARCHAR(40) NOT NULL,
  `destino` VARCHAR(40) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `precio` FLOAT NOT NULL,
  `descripcion` VARCHAR(280) NULL DEFAULT NULL,
  `idusuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idviaje`),
  UNIQUE INDEX `idviaje_UNIQUE` (`idviaje` ASC),
  INDEX `idusuario` (`idusuario` ASC),
  CONSTRAINT `viaje_ibfk_1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `aventon`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
